version: '2'
services:
  tocat:
    image: opswaycom/tocat:live
    links: 
      - mysql:db
    environment:
      - DB_USER=tocat
      - DB_PASS=password
      - DB_NAME=tocat_production
      - DB_PORT=3306
      - DB_HOST=db
      - SECRET_TOKEN=testtesttest
      - SECRET_TOKEN_BASE=testtesttest
    volumes:
      - /srv/tocat/log:/srv/tocat/log
    ports: 
      - "3000:3001"
    depends_on:
      - mysql

  mysql:
   image: mysql
   environment:
     - MYSQL_USER=tocat
     - MYSQL_PASSWORD=password
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=tocat_production
   volumes:
     - /home/vit/mysql:/var/lib/mysql
